{% set name = "libssh2" %}
{% set version = "1.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.libssh2.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  # Fix for CVE-2026-55200
  # https://github.com/libssh2/libssh2/pull/2052
  patches:
    - patches/0001-cve-2026-55200-transport-packet-length-bounds.patch
    # Fix for CVE-2025-15661
    # https://github.com/libssh2/libssh2/pull/1717
    - patches/0002-cve-2025-15661-sftp-symlink-oob-read.patch
    # Fix for CVE-2026-55199
    # https://github.com/libssh2/libssh2/commit/17626857d20b3c9a1addfa45979dadcee1cd84a4
    - patches/0003-cve-2026-55199-ext-info-string-parse-check.patch
    # Fix for CVE-2026-66032
    # https://github.com/libssh2/libssh2/pull/2180
    - patches/0004-cve-2026-66032-sftp-open-dangling-pointer.patch
    # Fix for CVE-2026-66033
    # https://github.com/libssh2/libssh2/commit/a2ed82d40964bbc0d64cd717aa0a5a892117d2e6
    - patches/0005-cve-2026-66033-openssl-aesgcm-oob-bounds.patch
    # Fix for CVE-2026-66034
    # https://github.com/libssh2/libssh2/commit/a13bb6c773f0d55ad1628cede57e99803cd898d9
    - patches/0006-cve-2026-66034-publickey-list-fetch-oob-read.patch
    # Fix for CVE-2026-66035
    # https://github.com/libssh2/libssh2/commit/42e33d81577ed4b95d4b4f6f845e5ee8efe5eeb4
    - patches/0007-cve-2026-66035-transport-etm-heap-overflow.patch
    # Fix for CVE-2026-7598
    # https://github.com/libssh2/libssh2/pull/1858
    - patches/0008-cve-2026-7598-userauth-username-len-bounds.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('libssh2') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # This breaks a dependency cycle:
    # curl->libssh2->cmake->curl
    - cmake-no-system
    - ninja-base
  host:
    - openssl {{ openssl }}
    - zlib {{ zlib }}
  run:
    # exact pin handled through openssl and zlib run_exports
    - openssl
    - zlib

test:
  commands:
    - test -f $PREFIX/include/libssh2.h              # [not win]
    - test -f $PREFIX/include/libssh2_publickey.h    # [not win]
    - test -f $PREFIX/include/libssh2_sftp.h         # [not win]

    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}        # [not win]
    - test -f $PREFIX/lib/pkgconfig/libssh2.pc       # [not win]

    - if not exist %LIBRARY_INC%\\libssh2.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1    # [win]
    - if not exist %LIBRARY_INC%\\libssh2_sftp.h exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\libssh2.lib exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libssh2.pc exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libssh2.dll exit 1            # [win]

about:
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'the SSH library'
  description: |
    libssh2 is a library implementing the SSH2 protocol, available under the revised BSD license.
  doc_url: https://www.libssh2.org/docs.html
  dev_url: https://github.com/libssh2/libssh2

extra:
  recipe-maintainers:
    - shadowwalkersb
