# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zidLfthcIxIbsjM/eBLbfKOHmEDKiCCzmdCb3/7uNscZGrHnn50//bkCttfEbeL13BeZp9QS1f66g0Icb16SCIZbgPKn4IlmDlbTdPW20RZ2XjxK69SePvMHhY27Fve8p/10gUdAFnlY3NvYlzkcTdB/UY/StGxw8iPjMfd98VWZ/RslGnKjf65mD2lATLhYA632fqVCPtM0qHTDCqGpEmGnBWzdanEstkNsNcSY0F9XFnrp8OegVNu/3QRBglgCiMAHGfHcOx01eFkQ9bFRzTI0zCoXi/8kpFkLS/ecuRCGFI9Kfhmzuyt9cFifXrJ8/fKIFYVFuZgaycGuyo73pJO2goC3Xj+a/TgImNb6SoU6gUG7/+hgxOqHe37GfxNs7vV3PEdXaF47YyiYUIm7RSqEfGaa0bQVqdrHkSRp6/V0pvhnj3EbBYNYyez8tUC424yFnmcLjHJzIgjrF7HjcI8mh977Ws63d0X9brJHtFmt1cCgdfRVtfkxbCesj/dAaf5S6ZT0U0h0FLNVomyKtmn7eV5JHZaLcb7VvUVauBh+ZjTJYIHExw7KpP9TTq+VzPSbNssDzp9HtMnMdNcGTs/4iKrLxS3qYEEUb8MTH3/VGEH1lEsH1+lvLSTwkfdoWs5OsvKxvwmbYc9n0vTCC1Goz5A1APTmJWKBTL0MpE0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
